name = "Wolf Logistics"
prefix = "wolf"
author = "Wolf Corps"
files = [
    "README.md",
    "LICENSE"
]

keyname = "{{prefix}}_{{version}}"
signame = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

releasebuild = [
    "@zip wolf_arsenalpoint_{{semver.major}}.{{semver.minor}}.{{semver.patch}}"
]

[header_exts]
version= "{{git \"id 8\"}}"
