name: Arma

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Lint (sqflint)
      uses: arma-actions/sqflint@master
      continue-on-error: true # No failure due to many false-positives

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Build using HEMTT
      uses: arma-actions/hemtt@master
      with:
        command: build --ci  # no --release due to https://github.com/synixebrett/HEMTT/issues/227
    # https://github.com/actions/upload-artifact/issues/3#issuecomment-524442814
    # - name: Upload Artifact
    #   uses: actions/upload-artifact@master
    #   with:
    #     name: ace3-${{ github.sha }}-nobin
    #     path: '@ace'
